name               = "testworker"               # Your Worker’s name in Cloudflare
main               = "src/index.js"             # Worker entry file
compatibility_date = "2025-04-21"               # YYYY-MM-DD (today or later)

account_id  = "8cf8307d5c06b5ed178b49ef076dc03e"               # From Dashboard → Workers → Overview
workers_dev = false                             # Deploy to your custom domain, not workers.dev

# Bind this Worker to any path under 8bit.am/search
route = { pattern = "8bit.am/search*", zone_name = "8bit.am" }