name               = "testworker"                    # matches your Worker name
main               = "src/index.js"                  # entry‑point
compatibility_date = "2025-04-21"                    # today’s date or later
account_id         = "8cf8307d5c06b5ed178b49ef076dc03e"             # Workers → Overview
workers_dev        = false                           # use your custom domain

# Bind only /search* on 8bit.am
route = { pattern = "8bit.am/search*", zone_name = "8bit.am" }